extends RefCounted
## Integrated flow checks; actual mouse gestures are also tested in the Web build.

const MAIN = preload("res://scenes/main.tscn")
const LEGACY_PAGES = [preload("res://data/pages/page_02.gd"), preload("res://data/pages/page_04.gd"), preload("res://data/pages/page_06.gd")]
const VALIDATOR = preload("res://core/page_validator.gd")
const SIM = preload("res://core/simulator.gd")
const GOALS = preload("res://core/goal_evaluator.gd")
const PLAN = preload("res://core/plan_state.gd")


func run(check: Callable) -> bool:
	load("res://game/main.gd").page_override = LEGACY_PAGES
	var game = MAIN.instantiate()
	(Engine.get_main_loop() as SceneTree).root.add_child(game)
	check.call(game.mode == "INTRO" and game.page.id == "page_02", "MVP launches directly into the first Original")
	check.call(game._story_waiting and game._voice.stream == null and game._voice_replay.text == "Start story", "Initial story waits for explicit audio-unlocking input")
	game._process(30.0)
	check.call(game._clock == 0.0 and game._voice.stream == null, "Waiting story does not queue autoplay or advance the Original")
	game._replay_voice()
	check.call(not game._story_waiting and game._last_cue == "narrator_intro", "Start story releases its explicit waiting state")
	for kind in ["MOVE", "EAT", "SIT", "BONK", "LAMP_ON"]:
		check.call(game._make_effect(kind).data.size() > 0, "%s has an original synthesized sound" % kind)
	check.call(game._run.has("presentation_frames") and not game._run.presentation_frames.is_empty(), "Playable flow requests recorded phase worlds")
	check.call(game._stage.size == Vector2(1280, 460), "Playable stage receives the full-width logical band")
	check.call(game._sound.get_theme_color("font_pressed_color") == game.INK, "Sound remains readable while pressed")
	check.call(game._hooks.size() == 2, "Both lanterns have HUD parking hooks")
	game._stop_voice()
	check.call(game._voice.stream == null and game._active_cue.is_empty(), "Skip voice clears the active stream")
	var click := InputEventMouseButton.new()
	click.button_index = MOUSE_BUTTON_LEFT
	click.pressed = true
	game._input(click)
	check.call(game.mode == "ORIGINAL_END", "Skipped Original presents its final evidence snapshot")
	game._process(0.61)
	check.call(game.mode == "PLAN" and game.attempts == 0, "Original returns to PLAN without consuming an attempt")
	for script in game.PAGE_SCRIPTS:
		check.call(VALIDATOR.new().validate(script.definition()).errors.is_empty(), "%s content validates" % script.definition().id)
	game._swap("boss", "dog")
	var winning_plan: Dictionary = game.plan.to_data()
	game._start_action()
	game._swap("boss", "dog")
	check.call(game.plan.to_data() == winning_plan, "Playback rejects thought edits")
	game._anticipation = 0.0
	game._process(0.15)
	var first_phase: Dictionary = game._run.presentation_frames[0]
	check.call(game._playback_world == first_phase.world, "Movement interpolation preserves the recorded DECIDE world")
	check.call(game._stage._world == first_phase.world, "Stage receives authoritative slots independently of visual movement")
	game._motion.button_pressed = true
	game._process(0.02)
	check.call(game._playback_world == first_phase.world, "Reduced motion does not advance simulation phases")
	game._motion.button_pressed = false
	game._finish_run()
	check.call(game.mode == "RESULT" and game.completed.has("page_02"), "One legal swap solves Nap Time's two facts")
	check.call(game._original_caption.text == GOALS.evaluate(game.page, game._original_run).caption, "Original uses the same recorded-event caption generator as Twist")
	check.call(game._last_cue == "narrator_success", "Nap Time success selects only its matching recorded ending")
	game._sound.button_pressed = false
	check.call(game._voice.stream == null and game._active_cue.is_empty(), "Sound off cancels voice")
	game._sound.button_pressed = true
	game._return_to_plan()
	check.call(game._voice.stream == null and game._subtitle.text.is_empty(), "REWIND clears voice and subtitles")
	check.call(game.plan.to_data() == winning_plan, "REWIND restores the exact committed plan")
	game._replay_original()
	check.call(not game._story_waiting, "Original replay does not repeat the launch prologue gate")
	game._finish_run()
	game._process(0.61)
	check.call(game.plan.to_data() == winning_plan and game.attempts == 1, "ORIGINAL preserves edited plan and attempt count")
	game._restart_page()
	check.call(game.plan.thoughts.boss == "HUNGRY" and game.plan.thoughts.dog == "SLEEPY", "RESTART restores default thoughts")
	check.call(game.plan.to_data().lanterns == game.page.lanterns.defaults, "RESTART restores both tutorial lanterns to their parked defaults")
	for i in range(3):
		game._start_action()
		game._finish_run()
		check.call("cross.svg" in game._facts.text, "Failed result marks unmet facts with a cross")
		game._return_to_plan()
	check.call(game.failures == 3 and not game._skip_page.disabled, "Skip page unlocks after three actual failures")
	check.call(game._next.disabled, "A past win does not enable NEXT on a later failed result")
	game._skip_current_page()
	game._finish_run()
	game._process(0.61)
	check.call(game.page.id == "page_04", "MVP advances to Midnight Snack")
	check.call("grandma" not in game._stage.revealed_thought_ids(), "Unlit Grandma's thought stays hidden after Original")
	game._move_lantern(1, Vector2(0.0, -0.6))
	check.call("grandma" in game._lit_ids(), "The second lantern can reveal a previously unlit character")
	var two_lantern_plan: Dictionary = game.plan.to_data()
	game._start_action()
	game._move_lantern(1, Vector2(4.0, 0.6))
	check.call(game.plan.to_data() == two_lantern_plan, "ACTION locks both lantern positions")
	game._finish_run()
	game._return_to_plan()
	check.call(game.plan.to_data() == two_lantern_plan, "REWIND restores the exact two-lantern plan")
	game._restart_page()
	check.call(game.plan.to_data().lanterns == game.page.lanterns.defaults, "RESTART restores both lantern positions and parked states")
	game._move_lantern(0, Vector2(1.0, -0.6))
	var before_preview: Dictionary = game.plan.to_data()
	var before_knowledge: Dictionary = game.knowledge.duplicate(true)
	game._preview("grandma", "kid")
	check.call(game.plan.to_data() == before_preview and game.knowledge == before_knowledge, "Swap preview mutates neither plan nor remembered knowledge")
	game._swap("grandma", "kid")
	game._move_lantern(0, Vector2(3.0, -0.6))
	var snack_plan: Dictionary = game.plan.to_data()
	game._start_action()
	game._move_lantern(0, Vector2(0.0, -0.6))
	check.call(game.plan.to_data() == snack_plan, "Playback rejects lantern edits")
	game._finish_run()
	check.call(game.completed.has("page_04"), "Midnight Snack's intended legal edit wins")
	game._next_page()
	game._finish_run()
	game._process(0.61)
	check.call(game.page.id == "page_06", "MVP advances to Birthday")
	var before_unreachable: Dictionary = game.plan.to_data()
	game._move_lantern(1, Vector2(9.0, -0.6))
	check.call(game.plan.to_data() == before_unreachable and "dog" not in game._lit_ids(), "Birthday placement bounds preserve the lamp-dependent Dog activation")
	game._move_lantern(0, Vector2(3.0, -0.6))
	game._swap("grandma", "boss")
	var birthday_plan: Dictionary = game.plan.to_data()
	game._start_action()
	while game.mode == "PLAY":
		game._process(0.4)
	check.call(game.completed.has("page_06") and game._run.end_beat == 8, "Full Birthday playback reaches the reference win")
	var full_result: Dictionary = game._run.duplicate(true)
	game._return_to_plan()
	game._start_action()
	game._finish_run()
	check.call(game._run == full_result, "Full playback and SKIP consume identical recorded runs")
	check.call(game.plan.to_data() == birthday_plan, "Playback leaves saved edit data intact")
	game._return_to_plan()
	game._move_lantern(0, Vector2(0.0, -0.6))
	game._replay_original()
	game._finish_run()
	game._process(0.61)
	check.call("boss" not in game._stage.revealed_thought_ids() and "grandma" not in game._stage.revealed_thought_ids(), "Original replay never exposes remembered thoughts in darkness")
	game._restart_page()
	check.call("grandma" not in game._stage.revealed_thought_ids(), "RESTART keeps Grandma's thought hidden at the default lantern positions")
	game._stage._drag_bubble = "grandma"
	game._stage._target = "boss"
	game._stage._cancel_drag()
	check.call(game._stage._drag_bubble.is_empty() and game._stage._target.is_empty(), "Focus-loss cancellation clears stale swap drag")
	game._stage._selected_lantern = 0
	game._stage._drag_bulb = 0
	var select_second := InputEventKey.new()
	select_second.pressed = true
	select_second.keycode = KEY_2
	game._stage._gui_input(select_second)
	check.call(game._stage._selected_lantern == 0, "Keyboard selection cannot redirect an ongoing lantern drag")
	game._stage._cancel_drag()
	var space := InputEventKey.new()
	space.pressed = true
	space.keycode = KEY_SPACE
	game._original.grab_focus()
	game._input(space)
	check.call(game.mode == "PLAY", "Global Space starts ACTION even when ORIGINAL has keyboard focus")
	game._input(space)
	check.call(game.mode == "RESULT", "Global Space skips recorded playback")
	game.free()
	load("res://game/main.gd").page_override = []
	return true
