"""Mirror the cast's reaction text (assets/audio/voice/cast_reactions.json) into lines.json.

lines.json drives the speech balloon text; the matching <art>_<reaction>.ogg files are
generated by .codex/tools/voice/generate_cast_sfx.py. Run after editing the JSON:
    python assets/audio/apply_cast_lines.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CAST = json.loads((ROOT / "assets/audio/voice/cast_reactions.json").read_text(encoding="utf-8"))
CAST.pop("note", None)
for path in (ROOT / "src/assets/audio/voice/lines.json", ROOT / "assets/audio/voice/lines.json"):
    if not path.exists():
        continue
    data = json.loads(path.read_text(encoding="utf-8"))
    for art, entry in CAST.items():
        data["characters"][art] = dict(entry["lines"])
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("updated", path)
